#[Info]
site_name: hinmouc's desk
site_url: #网站地址
site_author: hinmouc
site_description: 与梦想等价交易，与善良并肩同行

# 代码仓库信息
edit_uri: edit/main/docs            # 编辑按钮跳转的链接
repo_url: https://github.com/ # 右上角点击跳转的链接
repo_name: hinmouc.github.io # 右上角的名字


# 版权声明
copyright: Copyright &copy;  CC BY-NC-SA 4.0 # 左下角的版权声明.
# 高级版权配置
#extra:
#  copyright:
#    author: hinmouc
#    year: 2025
#    license: CC BY-NC-SA 4.0



# [Navigtion]
nav:
  - Me: index.md
  - Blog:
      - latex: reaserch/LaTeX.md
#      - test2: test/test2.md
  - other: about.md




#[UI]
theme:
   name: material
   font: false
     # font:
     #   text: JetBrains Mono
     #   code: Roboto Mono
     # font:
     #   text: Bitter
#   logo: https://pic4.zhimg.com/80/v2-a0456a5f527c1923f096759f2926012f_1440w.webp

   features:
     #导航相关
     - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
     - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
     - navigation.expand # 打开Tab时左侧目录全部展开
     - navigation.indexes #启用节索引页后，可以将文档直接附加到节
     - navigation.instant #- header.autohide  #自动隐藏
     - navigation.top # 返回顶部的按钮 在上滑时出现
#     - navigation.footer      # 上一页/下一页导航
     #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
     - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
#     - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见

     # 搜索相关
     - search.suggest # 搜索输入一些字母时推荐补全整个单词
     - search.highlight # 搜索出的文章关键词加入高亮
     - search.share #搜索分享按钮

     # 代码相关
     - content.code.annotate # 代码注释
     - content.code.copy    # 代码复制
     - content.tooltips
     - content.code.copy
     - content.code.select
#     - content.action.edit
     - content.action.view
      -
     # 其他功能
     - announce.dismiss     # 可关闭公告
     - header.autohide     # 自动隐藏头部

     # 配色方案
   palette:
     #primary: blue grey
     - scheme: default # 日间模式
       primary: white # 上方的
       accent: teal # 链接等可交互元件的高亮色
       toggle:
         icon: material/weather-night # 图标
         name: 切换至夜间模式 # 鼠标悬浮提示
     - scheme: slate # 夜间模式
       primary: blue grey #顶部颜色
       accent: cyan
       toggle:
         icon: material/weather-sunny
         name: 切换至日间模式      # 鼠标悬浮提示

     # 图标和字体
   icon:
      logo: material/book-open-page-variant # Logo图标
      repo: fontawesome/brands/github      # 仓库图标

   language: zh # 一些提示性的文字会变成中文





extra:
#  alternate:
#    - name: 简体中文
#      link: /
#      # https://wcowin-work.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
#      lang: zh
#    - name: English
#      link: /en/
#      # https://wcowin-work.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
#      lang: en
#    - name: ZH-TW
#      link: /ZH-TW/
#      # https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=zh-TW&_x_tr_hl=zh-CN&_x_tr_pto=wapp
#      lang: zh-TW
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/wcowin_
    - icon: fontawesome/brands/github
      link: https://github.com/hinmouc
#    - icon: fontawesome/brands/bilibili
#      link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
#    - icon: fontawesome/solid/paper-plane
#      link: mailto:<hingmauchan@163.com> #联系方式

plugins:
  - search
  - tags  #标签


markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  # - callouts
  - md_in_html
  - pymdownx.highlight     # 代码高亮
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.snippets     # 代码片段
  - pymdownx.magiclink    # 自动链接
  - pymdownx.mark        # ==标记==
  - pymdownx.critic      # 编辑标记
  - pymdownx.tilde      # 删除线
  - pymdownx.caret      # 上标
  - pymdownx.keys       # 键盘按键
  - pymdownx.tabbed    # 标签页
  - pymdownx.arithmatex: # latex支持
      generic: true
#  - toc:
#      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

#markdown_extensions:
#  - abbr
#  - attr_list
#  - admonition
#  - def_list
#  - footnotes
#  # - callouts
#  - md_in_html
#  - markdown.extensions.abbr # 支持Markdown文件上方自定义标题标签等
#  - pymdownx.magiclink
#  - pymdownx.caret
#  - pymdownx.betterem
#  - pymdownx.critic
#  - pymdownx.details
#  - pymdownx.inlinehilite
#  - pymdownx.keys
#  - pymdownx.mark
#  - pymdownx.snippets
#  - pymdownx.smartsymbols
#  - pymdownx.tilde
#
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format
#  - pymdownx.arithmatex:  # latex支持
#      generic: true
#  - toc:
#      permalink: true # 固定标题位置为当前位置
#  - pymdownx.highlight: # 代码块高亮
#      anchor_linenums: true
#      linenums: true # 显示行号
#      # auto_title: true # 显示编程语言名称
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#  - pymdownx.tabbed:
#      alternate_style: true
#  - pymdownx.tasklist:
#      custom_checkbox: true

#markdown_extensions:
#  - abbr
#  - pymdownx.caret
#  - pymdownx.mark
#  - pymdownx.tilde
#  - md_in_html
#  - pymdownx.arithmatex:  # latex支持
#      generic: true
#  - toc:
#      permalink: true # 固定标题位置为当前位置
#  - pymdownx.highlight: # 代码块高亮
#      anchor_linenums: true
#      # linenums: true # 显示行号
#      # auto_title: true # 显示编程语言名称
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.superfences
#  - attr_list
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
#  - pymdownx.superfences # 代码块高亮插件
#  - meta # 支持Markdown文件上方自定义标题标签等

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
